// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentStatus = "published" | "draft" | "deprecated";

export type Deprecation = { reason: string, replaced_by?: string | null, };

/**
 * Question kinds.
 */
export type License = "CC0-1.0" | "CC-BY-4.0" | "CC-BY-SA-4.0" | "CC-BY-NC-4.0" | "CC-BY-ND-4.0" | "MIT";

export type NormalizeOp = "lowercase" | "strip_diacritics" | "strip_punctuation" | "strip_whitespace" | "strip_articles";

export type QuestionKind = "text" | "numeric" | "order";

export type Source = { url: string, accessed?: string | null, note?: string | null, };

export type VariantName = "multiple_choice" | "true_false" | "open" | "numeric_input" | "range";
