// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reference to a resource that depends on the item being deleted.
 */
export type Dependent = { kind: string, id: string, };

export type DependentsError = { dependents: Array<Dependent>, };

export type FieldError = { path: string, message: string, };

export type ValidationError = Array<FieldError>;
