// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Game = { id: string, title: string, description: string, auto_advance: boolean, modes: Array<string>, tags: Array<TagDto>, question_count: number | null, entries: Array<GameEntry>, };

export type GameEntry = { title: string, mode: string, question_count: number | null, tags: Array<TagDto>, };

/**
 * Tag id + label. `id` is the stable `category:slug`; `label` is localized.
 */
export type TagDto = { id: string, label: string, };
