// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentStatus, VariantName } from "./Common";
import type { PackFilter } from "./Packs";

export type Board = { difficulty_map?: { [key in number]: Array<string> } | null, points: Array<number>, categories: Array<BoardCategory>, };

export type BoardCategory = { name: string, question_ids?: { [key in number]: BoardCell } | null, pack_ref?: string | null, filter?: PackFilter | null, };

export type BoardCell = { id: string, variant?: VariantName | null, };

/**
 * Who gets the floor when a question goes live.
 */
export type BuzzPolicy = "open_floor" | "turn_order" | "broadcast";

export type Game = { title: string, rules: Rules, mode: GameMode, };

/**
 * Top-level game config, parsed from `data/games/*.yaml`.
 */
export type GameConfig = { id: string, title: string, description: string, auto_advance: boolean, games: Array<Game>, status: ContentStatus, };

/**
 * A single game in the chain. Each has its own mode, rules, and content.
 */
export type GameMode = { "kind": "grid_quiz" } & GridQuizGame | { "kind": "linear" } & LinearGame;

/**
 * Grid quiz: inline board definition.
 */
export type GridQuizGame = { grid_rules: GridQuizRules, board: Board, };

/**
 * grid_quiz-specific rules, separate from the shared `Rules` (linear has no
 * cells to pick). Defaults from the manifest; host may override per session.
 */
export type GridQuizRules = { picker_mode: PickerMode, 
/**
 * `None` = manual (mod advances Reveal); `Some(n)` = auto-advance after n secs.
 */
reveal_auto_advance_secs?: number | null, };

/**
 * How answers are judged.
 */
export type Judge = "auto" | "moderator";

/**
 * Linear quiz: resolved question list.
 */
export type LinearGame = { questions: LinearSource, };

export type LinearSource = { "source": "questions", question_ids: Array<string>, } | { "source": "pack", pack_id: string, } | { "source": "filter", filter: PackFilter, };

/**
 * What happens after a wrong answer.
 */
export type LockoutPolicy = "none" | "this_question" | "this_round";

/**
 * Who picks the next cell in grid_quiz. Independent of the answer-side buzz
 * policy — see `docs/game-flow.md` §Picker modes.
 */
export type PickerMode = "rotate" | "winner_picks";

/**
 * Per-entry game rules. Complete, no merging with defaults.
 */
export type Rules = { buzz_policy: BuzzPolicy, scoring_mode: ScoringMode, lockout_policy: LockoutPolicy, steal_policy: StealPolicy, judge: Judge, question_timer_secs: number, answer_timer_secs: number, };

/**
 * How points are decided for a question.
 */
export type ScoringMode = "first_correct" | "all_grade" | "closest_wins";

/**
 * After wrong answer, does floor reopen?
 */
export type StealPolicy = "none" | "open_floor" | "round_limited";
