// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Media = { kind: MediaKind, ref: string, alt?: string | null, width?: number | null, height?: number | null, };

export type MediaKind = "image" | "audio" | "video";
