// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Media } from "./Media";

export type BoardCategoryOverlay = { name: string | null, };

export type BoardOverlay = { categories: Array<BoardCategoryOverlay>, };

export type ChoiceOverlay = { id: string, text: string | null, media: Array<Media> | null, };

export type ContentOverlay = { answer: string | null, explanation: string | null, prompt: PromptOverlay | null, unit: string | null, items: Array<OrderItemOverlay> | null, variants: VariantsOverlay | null, };

export type GameConfigOverlay = { id: string, title: string | null, description: string | null, games: Array<GameOverlay>, };

export type GameOverlay = { title: string | null, board: BoardOverlay | null, };

export type MultipleChoiceOverlay = { choices: Array<ChoiceOverlay>, };

export type OpenVariantOverlay = { accepted: Array<string> | null, };

export type OrderItemOverlay = { id: string, text: string | null, media: Array<Media> | null, };

export type PackOverlay = { id: string, title: string | null, description: string | null, };

export type PromptOverlay = { text: string | null, media: Array<Media> | null, };

/**
 * Translatable subset of a question — no `correct`, `position`, numeric
 * `answer`, variant config, or metadata fields.
 */
export type QuestionOverlay = { id: string, content: ContentOverlay, };

export type TagOverlay = { id: string, label: string | null, description: string | null, };

export type VariantsOverlay = { multiple_choice: MultipleChoiceOverlay | null, open: OpenVariantOverlay | null, };
