// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentStatus, License, QuestionKind, VariantName } from "./Common";

export type Pack = { id: string, title: string, author?: string | null, description?: string | null, license?: License | null, default_lang?: string | null, recommended_gamemodes?: Array<string> | null, includes?: Array<string> | null, questions?: Array<string> | null, filter?: PackFilter | null, status: ContentStatus, };

export type PackFilter = { kinds?: Array<QuestionKind> | null, tags_all?: Array<string> | null, tags_any?: Array<string> | null, tags_none?: Array<string> | null, variants_any?: Array<VariantName> | null, limit?: number | null, };
