// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { id: string, label: string, default_lang: string, description: string | null, };
