// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRoom = { game_id: string, secret: string | null, };

export type Room = { join_code: string, };
