// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adjudication outcome. `Pending` is transient (awaits a moderator ruling or a
 * timer-driven auto-verdict); the rest are final. Stored in the judgment log;
 * `score = fold(log)`.
 */
export type Verdict = "correct" | "incorrect" | "void" | "pending";
